on:
  - pull_request

jobs:
  lint-code-of-conduct:
    name: Lint changelog file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint code of conduct
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        args: './code-of-conduct.md'